package Pruebas;
import java.sql.Date;
import java.util.LinkedList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import Entidades.Alumno;
import Entidades.Expediente;
import Entidades.Grupo;
import Entidades.Matricula;
import Entidades.MatriculaPK;

public class Base {
	public static void init(String nombreper) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory(nombreper);
		EntityManager em = emf.createEntityManager();
		Date d = new Date(System.currentTimeMillis());
		Alumno a1 = new Alumno("Mario", "Vazquez", "12345678a", "mario@uma.es");
		Alumno a2 = new Alumno("Juan", "Moreno", "23456789b", "juan@uma.es");
		Alumno a3 = new Alumno("Marta", "Ruiz", "34567890c", "marta@uma.es");
		Alumno a4 = new Alumno("Pedro", "MuÒoz", "45678901d", "pedro@uma.es");
		Alumno a5 = new Alumno("Maria", "Garcia","56789012e", "maria@uma.es");
		Alumno a6 = new Alumno("Luis", "Ramos", "67890123f", "luis@uma.es");
		Expediente e1 = new Expediente((long)214623,true,5.0);
		Expediente e2 = new Expediente((long)172411,true,5.0);
		Expediente e3 = new Expediente((long)238413,true,5.0);
		Expediente e4 = new Expediente((long)872163,true,5.0);
		Expediente e5 = new Expediente((long)174615,true,5.0);
		Expediente e6 = new Expediente((long)123642,true,5.0);
		List<Matricula> mats = new LinkedList<>();
		MatriculaPK pk = new MatriculaPK("2∫", (long)214623);
		Matricula m1 = new Matricula(pk,e1,'I',d);
		mats.add(m1);
		e1.setMatricula(mats);
		e1.setAlumno(a1);
		pk = new MatriculaPK("1∫", (long)214623);
		Matricula m2 = new Matricula(pk,e2,'I',d);
		mats.remove(0);
		mats.add(m2);
		e2.setMatricula(mats);
		e2.setAlumno(a2);
		pk = new MatriculaPK("3∫", (long)172411);
		Matricula m3 = new Matricula(pk,e3,'I',d);
		mats.remove(0);
		mats.add(m3);
		e3.setMatricula(mats);
		e3.setAlumno(a3);
		pk = new MatriculaPK("4∫", (long)872163);
		Matricula m4 = new Matricula(pk,e4,'I',d);
		mats.remove(0);
		mats.add(m4);
		e4.setMatricula(mats);
		e4.setAlumno(a4);
		pk = new MatriculaPK("2∫", (long)174615);
		Matricula m5 = new Matricula(pk,e5,'I',d);
		mats.remove(0);
		mats.add(m5);
		e5.setMatricula(mats);
		e5.setAlumno(a5);
		pk = new MatriculaPK("1∫", (long)123642);
		Matricula m6 = new Matricula(pk,e6,'I',d);
		mats.remove(0);
		mats.add(m6);
		e6.setMatricula(mats);
		e6.setAlumno(a6);
		Grupo a = new Grupo("2∫", "a","Ma√±ana");
		Grupo b = new Grupo("1∫", "b","Ma√±ana");
		Grupo c = new Grupo("1∫", "c","Tarde");		
		List<Expediente> exps = new LinkedList<>();
		List<Grupo> gps = new LinkedList<>();
		exps.add(e1);
		a1.setExpedientes(exps);
		exps.remove(0);
		exps.add(e2);
		a2.setExpedientes(exps);
		exps.remove(0);
		exps.add(e3);
		a3.setExpedientes(exps);
		exps.remove(0);
		exps.add(e4);
		a4.setExpedientes(exps);
		exps.remove(0);
		exps.add(e5);
		a5.setExpedientes(exps);
		exps.remove(0);
		exps.add(e6);
		a6.setExpedientes(exps);
		gps.add(a);
		a1.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(b);
		a2.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(c);
		a3.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(b);
		a4.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(a);
		a5.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(a);
		a6.setAlumno_Grupos(gps);
		em.getTransaction().begin();
		em.persist(m1);
		em.persist(m2);
		em.persist(m3);
		em.persist(m4);
		em.persist(m5);
		em.persist(m6);
		em.persist(a);
		em.persist(b);
		em.persist(c);
		em.persist(e1);
		em.persist(e2);
		em.persist(e3);
		em.persist(e4);
		em.persist(e5);
		em.persist(e6);
		em.persist(a1);
		em.persist(a2);
		em.persist(a3);
		em.persist(a4);
		em.persist(a5);
		em.persist(a6);
				
		em.getTransaction().commit();
		em.close();
		emf.close();
	}
}
