package Pruebas;
import java.sql.Date;
import java.util.LinkedList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import Entidades.*;
import Entidades.Encuesta.Expediente_Encuesta_PK;
public class Base {
	public static void init(String nombreper) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory(nombreper);
		EntityManager em = emf.createEntityManager();
		Date d = new Date(System.currentTimeMillis());
		Alumno a1 = new Alumno("Mario", "Vazquez", "12345678a", "mario@uma.es");
		Alumno a2 = new Alumno("Juan", "Moreno", "23456789b", "juan@uma.es");
		Alumno a3 = new Alumno("Marta", "Ruiz", "34567890c", "marta@uma.es");
		Alumno a4 = new Alumno("Pedro", "Muñoz", "45678901d", "pedro@uma.es");
		Alumno a5 = new Alumno("Maria", "Garcia","56789012e", "maria@uma.es");
		Alumno a6 = new Alumno("Luis", "Ramos", "67890123f", "luis@uma.es");
		
		Expediente e1 = new Expediente((long)214623,true,5.0);
		Expediente e2 = new Expediente((long)172411,true,5.0);
		Expediente e3 = new Expediente((long)238413,true,5.0);
		Expediente e4 = new Expediente((long)872163,true,5.0);
		Expediente e5 = new Expediente((long)174615,true,5.0);
		Expediente e6 = new Expediente((long)123642,true,5.0);
		
		Encuesta en1 = new Encuesta(d,e1, "Manyana");
		Encuesta en2 = new Encuesta(d,e2, "Manyana");
		Encuesta en3 = new Encuesta(d,e3, "Manyana");
		Encuesta en4 = new Encuesta(d,e4, "Tarde");
		Encuesta en5 = new Encuesta(d,e5, "Tarde");
		Encuesta en6 = new Encuesta(d,e6, "Manyana");
		
		List<Encuesta> p = new LinkedList<>();
		p.add(en1);
		e1.setEncuesta(p);
		p.remove(en1);
		p.add(en2);
		e2.setEncuesta(p);
		p.remove(en2);
		p.add(en3);
		e3.setEncuesta(p);
		p.remove(en3);
		p.add(en4);
		e4.setEncuesta(p);
		p.remove(en4);
		p.add(en5);
		e5.setEncuesta(p);
		p.remove(en5);
		p.add(en6);
		e6.setEncuesta(p);
		Titulacion t =  new Titulacion("Desarrollo movil",550);
		Asignatura as = new Asignatura("rf12","Desarrollo de maquinas virtuales",9999,12,true,false);
		List<Asignatura> asig = new LinkedList<>();
		asig.add(as);
		t.setAsignaturas(asig);
		e1.setTitulacion(t);
		e2.setTitulacion(t);
		e3.setTitulacion(t);
		List<Matricula> mats = new LinkedList<>();
		MatriculaPK pk = new MatriculaPK("2º", (long)214623);
		Matricula m1 = new Matricula(pk,e1,'I',d);
		mats.add(m1);
		e1.setMatricula(mats);
		e1.setAlumno(a1);
		pk = new MatriculaPK("1º", (long)214623);
		Matricula m2 = new Matricula(pk,e2,'I',d);
		mats.remove(0);
		mats.add(m2);
		e2.setMatricula(mats);
		e2.setAlumno(a2);
		pk = new MatriculaPK("2º", (long)172411);
		Matricula m3 = new Matricula(pk,e3,'I',d);
		mats.remove(0);
		mats.add(m3);
		e3.setMatricula(mats);
		e3.setAlumno(a3);
		pk = new MatriculaPK("1º", (long)872163);
		Matricula m4 = new Matricula(pk,e4,'I',d);
		mats.remove(0);
		mats.add(m4);
		e4.setMatricula(mats);
		e4.setAlumno(a4);
		pk = new MatriculaPK("2º", (long)174615);
		Matricula m5 = new Matricula(pk,e5,'I',d);
		mats.remove(0);
		mats.add(m5);
		e5.setMatricula(mats);
		e5.setAlumno(a5);
		pk = new MatriculaPK("1º", (long)123642);
		Matricula m6 = new Matricula(pk,e6,'I',d);
		mats.remove(0);
		mats.add(m6);
		e6.setMatricula(mats);
		e6.setAlumno(a6);
		Grupo a = new Grupo("2º", "a","Manyana");
		Grupo b = new Grupo("1º", "b","Manyana");
		Grupo c = new Grupo("1º", "c","Tarde");
		a.setPlazasNuevoIngreso((long)5);
		a.setPlazasRepetidores((long)1);
		List<Expediente> exps = new LinkedList<>();
		List<Grupo> gps = new LinkedList<>();
		exps.add(e1);
		a1.setExpedientes(exps);
		exps.remove(0);
		exps.add(e2);
		a2.setExpedientes(exps);
		exps.remove(0);
		exps.add(e3);
		a3.setExpedientes(exps);
		exps.remove(0);
		exps.add(e4);
		a4.setExpedientes(exps);
		exps.remove(0);
		exps.add(e5);
		a5.setExpedientes(exps);
		exps.remove(0);
		exps.add(e6);
		a6.setExpedientes(exps);
		gps.add(a);
		a1.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(b);
		a2.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(c);
		a3.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(b);
		a4.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(a);
		a5.setAlumno_Grupos(gps);
		gps.remove(0);
		gps.add(c);
		a6.setAlumno_Grupos(gps);
		Grupos_Por_Asignatura g1 = new Grupos_Por_Asignatura("20/21",a,as);
		Grupos_Por_Asignatura g2 = new Grupos_Por_Asignatura("20/21",b,as);
		Grupos_Por_Asignatura g3 = new Grupos_Por_Asignatura("20/21",c,as);
		List<Grupos_Por_Asignatura> gpa = new LinkedList<>();
		gpa.add(g1);
		gpa.add(g2);
		gpa.add(g3);
		as.setGpa(gpa);
		a.setGpa(gpa);
		b.setGpa(gpa);
		c.setGpa(gpa);
		
		
		em.getTransaction().begin();
		em.persist(t);
		em.persist(as);
		em.persist(m1);
		em.persist(m2);
		em.persist(m3);
		em.persist(m4);
		em.persist(m5);
		em.persist(m6);
		em.persist(a);
		em.persist(b);
		em.persist(c);
		em.persist(e1);
		em.persist(e2);
		em.persist(e3);
		em.persist(e4);
		em.persist(e5);
		em.persist(e6);
		em.persist(a1);
		em.persist(a2);
		em.persist(a3);
		em.persist(a4);
		em.persist(a5);
		em.persist(a6);
		em.persist(g1);
		em.persist(g2);
		em.persist(g3);
		em.persist(en1);
		em.persist(en2);
		em.persist(en3);
		em.persist(en4);
		em.persist(en5);
		em.persist(en6);
				
		em.getTransaction().commit();
		em.close();
		emf.close();
	}
}
