// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ImportacionAsignaturasTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void importacionAsignaturas() {
    driver.get("http://0.0.0.0:8080/AsignacionGrupos-war/faces/Login.xhtml");
    driver.manage().window().setSize(new Dimension(911, 947));
    driver.findElement(By.id("myform:username")).click();
    driver.findElement(By.id("myform:username")).sendKeys("secretaria");
    driver.findElement(By.id("myform:login")).sendKeys("secretaria");
    driver.findElement(By.id("myform:iniciarses")).click();
    driver.findElement(By.id("carousel_2d7f")).click();
    driver.findElement(By.cssSelector(".u-expanded-width-md:nth-child(1) .u-container-layout")).click();
    driver.findElement(By.id("import_form_asignaturas:fileAsignaturas")).click();
    driver.findElement(By.id("import_form_asignaturas:fileAsignaturas")).sendKeys("C:\\fakepath\\Asignaturas.xlsx");
    driver.findElement(By.id("import_form_asignaturas:boton")).click();
    driver.findElement(By.cssSelector(".u-container-layout-5")).click();
    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".ui-widget-content:nth-child(1) > td:nth-child(2)")).getText(), is("104"));
  }
}
