// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InsertarYborrarAsignaturaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void insertarYborrarAsignatura() {
    driver.get("http://0.0.0.0:8080/AsignacionGrupos-war/faces/insertarAsignatura.xhtml");
    driver.findElement(By.name("j_idt6:j_idt10")).click();
    driver.findElement(By.name("j_idt6:j_idt10")).sendKeys("000001");
    driver.findElement(By.name("j_idt6:j_idt14")).click();
    driver.findElement(By.name("j_idt6:j_idt14")).sendKeys("00000002");
    driver.findElement(By.name("j_idt6:j_idt18")).click();
    driver.findElement(By.name("j_idt6:j_idt18")).click();
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt18"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("j_idt6:j_idt18")).sendKeys("6");
    driver.findElement(By.name("j_idt6:j_idt22")).click();
    driver.findElement(By.name("j_idt6:j_idt22")).sendKeys("Programacion");
    {
      WebElement dropdown = driver.findElement(By.name("j_idt6:j_idt26"));
      dropdown.findElement(By.xpath("//option[. = 'Si']")).click();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt26"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt26"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt26"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("j_idt6:j_idt26")).click();
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt32"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt32"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt32"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("j_idt6:j_idt32")).click();
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt40"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt40"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt40"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("j_idt6:j_idt40")).click();
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt47"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt47"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt47"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("j_idt6:j_idt47")).click();
    {
      WebElement dropdown = driver.findElement(By.name("j_idt6:j_idt53"));
      dropdown.findElement(By.xpath("//option[. = 'Si']")).click();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt53"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt53"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.name("j_idt6:j_idt53"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.name("j_idt6:j_idt53")).click();
    driver.findElement(By.name("j_idt6:j_idt59")).click();
    driver.findElement(By.name("j_idt6:j_idt59")).sendKeys("1041");
    driver.findElement(By.name("j_idt6:j_idt61")).click();
    driver.findElement(By.cssSelector(".u-container-layout-5")).click();
    driver.findElement(By.cssSelector(".ui-widget-content:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".ui-widget-content:nth-child(1) > td:nth-child(1)")).getText(), is("000001"));
    driver.findElement(By.id("j_idt65:listasg:0:elimbtn")).click();
    driver.findElement(By.id("j_idt65:listasg:referencia:filter")).click();
    driver.findElement(By.id("j_idt65:listasg:referencia:filter")).sendKeys("000");
    driver.findElement(By.cssSelector(".ui-widget-content > td")).click();
    assertThat(driver.findElement(By.cssSelector(".ui-widget-content > td")).getText(), is(not("No records found.")));
  }
}
